# Generated by Django 2.0.5 on 2018-11-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdata',
            name='token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
