# Generated by Django 2.0.5 on 2018-11-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181127_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='code',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='token',
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
