# Generated by Django 2.0.5 on 2018-11-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181127_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='varified',
            field=models.NullBooleanField(),
        ),
    ]
