# Generated by Django 2.0.5 on 2018-11-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181127_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
