# Generated by Django 2.0.5 on 2018-11-30 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tokenholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
